site_name: Soviet-Docs
markdown_extensions: 
  - pymdownx.escapeall:
      hardbreak: True
theme:
  logo: https://github.com/JohnVictoryz/Soviet-Docs/blob/main/Soviet-Logo.png?raw=true 
  name: material
  palette:
    scheme: slate